"""add performance_log table

Revision ID: 410784c8f154
Revises: c69d28f60b34
Create Date: 2026-03-11 14:11:29.851672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410784c8f154'
down_revision: Union[str, Sequence[str], None] = 'c69d28f60b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('retention_before', sa.Float(), nullable=True),
    sa.Column('retention_after', sa.Float(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_log_session_id'), 'performance_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_performance_log_topic_id'), 'performance_log', ['topic_id'], unique=False)
    op.create_index(op.f('ix_performance_log_user_id'), 'performance_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_log_user_id'), table_name='performance_log')
    op.drop_index(op.f('ix_performance_log_topic_id'), table_name='performance_log')
    op.drop_index(op.f('ix_performance_log_session_id'), table_name='performance_log')
    op.drop_table('performance_log')
    # ### end Alembic commands ###
