"""Add correct_answer to questions table

Revision ID: c69d28f60b34
Revises: a80a78c96fb3
Create Date: 2026-03-09 15:06:02.107639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69d28f60b34'
down_revision: Union[str, Sequence[str], None] = 'a80a78c96fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct_answer', sa.String(), server_default='A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'correct_answer')
    # ### end Alembic commands ###
