"""Add topic_id to quiz_sessions

Revision ID: cdfa3609bd7f
Revises: 2d9a0c8b654c
Create Date: 2026-03-09 00:32:43.565769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfa3609bd7f'
down_revision: Union[str, Sequence[str], None] = '2d9a0c8b654c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('topic_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_quiz_sessions_topic_id'), 'quiz_sessions', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'quiz_sessions', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_sessions_topic_id'), table_name='quiz_sessions')
    op.drop_column('quiz_sessions', 'topic_id')
    # ### end Alembic commands ###
